/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class AllFlow2UI extends Laya.Scene {
		public bgImg:Laya.Image;
		public btnClose:Laya.Button;
		public btnClosejia:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("AllFlow2");
        }
    }
    REG("ui.AllFlow2UI",AllFlow2UI);
    export class AllFlowsUI extends Laya.Dialog {
		public bgImg:Laya.Image;
		public btnClose:Laya.Button;
		public btnClosejia:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("AllFlows");
        }
    }
    REG("ui.AllFlowsUI",AllFlowsUI);
    export class AllFlows1UI extends Laya.Dialog {
		public bgImg:Laya.Image;
		public xinyou:Laya.Image;
		public btnClose:Laya.Button;
		public btnClosejia:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("AllFlows1");
        }
    }
    REG("ui.AllFlows1UI",AllFlows1UI);
    export class AllFlows3UI extends Laya.Dialog {
		public bgImg:Laya.Image;
		public btnClose:Laya.Button;
		public btnClosejia:Laya.Button;
		public flowBottom:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("AllFlows3");
        }
    }
    REG("ui.AllFlows3UI",AllFlows3UI);
    export class FullSceneFlowsUI extends Laya.Dialog {
		public bgImg:Laya.Image;
		public btnBack:Laya.Button;
		public flowBottom:Laya.Image;
		public btnClose:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("FullSceneFlows");
        }
    }
    REG("ui.FullSceneFlowsUI",FullSceneFlowsUI);
    export class LaunchUI extends Laya.Scene {
		public logoAnim:Laya.FrameAnimation;
		public bg:Laya.Image;
		public logo:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Launch");
        }
    }
    REG("ui.LaunchUI",LaunchUI);
    export class WuDianUI extends Laya.Scene {
		public progressUI:Laya.Image;
		public bar:Laya.Image;
		public btnClick:Laya.Button;
		public btnModel:Laya.Image;
		public shou:Laya.Image;
		public flowBottom:Laya.Image;
		public title:Laya.Label;
		public banner:Laya.Image;
		public reward:Laya.Box;
		public btnClose:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("WuDian");
        }
    }
    REG("ui.WuDianUI",WuDianUI);
}