/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AllFlow2 from "./script/center/export/AllFlow2"
import FlowManager from "./script/center/export/FlowManager"
import ButtonDonghua from "./script/center/view/ButtonDonghua"
import AllFlows from "./script/center/export/AllFlows"
import BannerNode from "./script/center/ad/BannerNode"
import FullSceneFlows from "./script/center/export/FullSceneFlows"
import GameFighting from "./script/views/GameFighting"
import FlowTeamChange from "./script/center/export/FlowTeamChange"
import GameOver from "./script/views/GameOver"
import Login from "./script/center/view/Login"
import NoShowUISwitch from "./script/mgr3d/NoShowUISwitch"
import MainView from "./script/views/MainView"
import Fuhuo from "./script/center/view/Fuhuo"
import RewardView from "./script/views/RewardView"
import ButtonAnim from "./script/views/ButtonAnim"
import Skin111 from "./script/center/view/Skin111"
import SkinTrial from "./script/views/SkinTrial"
import TipView from "./script/views/TipView"
import WuDian from "./script/center/view/WuDian"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Launch.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/center/export/AllFlow2.ts",AllFlow2);
        reg("script/center/export/FlowManager.ts",FlowManager);
        reg("script/center/view/ButtonDonghua.ts",ButtonDonghua);
        reg("script/center/export/AllFlows.ts",AllFlows);
        reg("script/center/ad/BannerNode.ts",BannerNode);
        reg("script/center/export/FullSceneFlows.ts",FullSceneFlows);
        reg("script/views/GameFighting.ts",GameFighting);
        reg("script/center/export/FlowTeamChange.ts",FlowTeamChange);
        reg("script/views/GameOver.ts",GameOver);
        reg("script/center/view/Login.ts",Login);
        reg("script/mgr3d/NoShowUISwitch.ts",NoShowUISwitch);
        reg("script/views/MainView.ts",MainView);
        reg("script/center/view/Fuhuo.ts",Fuhuo);
        reg("script/views/RewardView.ts",RewardView);
        reg("script/views/ButtonAnim.ts",ButtonAnim);
        reg("script/center/view/Skin111.ts",Skin111);
        reg("script/views/SkinTrial.ts",SkinTrial);
        reg("script/views/TipView.ts",TipView);
        reg("script/center/view/WuDian.ts",WuDian);
    }
}
GameConfig.init();